version: '3'
services:
  mysql:
    image: mysql:latest
    env_file:
      - .env
    ports:
      - "8001:3306"  # Mapping MySQL port
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
  
  workiz-fetcher:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ./app:/app
      - ./crontab:/etc/cron.d/cron-job
    #    command: bash -c "cron && tail -f /var/log/cron.log"
      - ./wait-for-it.sh:/wait-for-it.sh  # Add this line
    command: bash -c "/wait-for-it.sh mysql:3306 -- python /app/main.py"
    depends_on:
      - mysql


volumes:
  mysql_data:
    driver: local
