version: '3'
services:
  workiz-fetcher:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ./app:/app
      - ./crontab:/etc/cron.d/cron-job
    #    command: bash -c "cron && tail -f /var/log/cron.log"
    command: bash -c "python /app/main.py"
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    env_file:
      - .env
    ports:
      - "8001:3306"  # Mapping MySQL port
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
